{{< include _includes/_front_matter.qmd >}}
{{< include _includes/_init_fontawesome.qmd >}} 
{{< include _includes/_katex_macros.qmd >}} 
{{< include _includes/_r_themes.qmd >}}

## Situation

Trotz der Tatsachen, dass die Biologie

- eine allumfassende Naturwissenschaft ist und mit dem Humangenomprojekt alle Megaprojekte des letzten Jahrhunderts in den Schatten stellt,
- mit massiv parallelen molekularen Verfahren Erkenntnisgewinn und medizinische Diagnostik vorantreibt
- bei der Aufklärung von Krankheiten wie Krebs und bei der Bekämpfung von Infektionskrankheiten ein entscheidende Rolle spielt,
- und ihre Makromoleküle bereits mehr als 50% aller neuer Arzneimittelzulassungen ausmacht,
- wichtigste Beiträge zum Verständnis von Ökosystemen und Nachhaltigkeit liefert,
- eine Industrie mit dreifach bis zehnfach höheren Zuwächsen als die chemische Industrie ermöglicht,

hat sich das Saarland entschieden, die Biologie als eine sekundäre Naturwissenschaft zu betrachten. Die Biologie ist nicht direkt relevant für das Erreichen der A Kurse. Dies ist alleine Physik und Chemie vorbehalten neben Mathematik, Deutsch, und einer Fremdsprache.

Falls Du um das Erreichen von A Kursen kämpfst, fokussiere primär auf diese fünf Fächer. Solltest Du jedoch aus irgendeinem Grund statt fünf nur vier A Kurse im Verlauf der Stufe 10 einholen, dann tritt an unserer Schule ein besonderes Verfahren in Kraft. 

Es kann in einer pädagogischen Entscheidung bei einem entsprechenden Notendurchschnitt in allen übrigen Fächern zu einer Neueinstufung kommen. Diese Neueinstufung setzt alle relevanten fünf Fächer auf A Kursniveau. Um diese Neueinstufung überhaupt wahrnehmen zu können, musst Du in Biologie, aber auch in Gesellschaftswissenschaften und anderen Fächern, eine gute bis sehr gute Leistung zeigen. Deswegen ist eine grundsätzlich gesunde Arbeitseinstellung hilfreich.

## Erwartung

Reiche die Antworten als digitales Dokument ein, wie in der entsprechenden Aufgabe im Lernmodul auf *Teams* beschrieben. Es gibt dabei zwei grundsätzliche Arten von Aufgaben: die erste ist etwas einfacher und erfordert die Wiedergabe von Fakten und Rechenwegen. Die zweite Art erfordert, dass Du Probleme löst. Das ist auch die Art, die Dir später in Beruf, Forschung und Entwicklung, Management, usw. begegnen wird. Bei der letzteren gibt es grundsätzlich mehr Punkte.

### Verhalten bei Schwierigkeiten

Falls Du Schwierigkeiten hast, musst Du diese proaktiv Deinem Fachlehrer mitteilen und angehen. Am besten machst Du das schriftlich über *Teams*. Wenn Du dies nicht mindestens 48 Stunden vor Abgabe machst, dann wird Deine Leistung entsprechend benotet. 

### Beantwortung der Aufgabe mit Text

Fragen nach Erläuterungen und Beschreibungen werden mithilfe von Fachbegriffen beantwortet. Gibt es eine richtige Beschreibung aber keine Fachbegriffe, dann bekommst Du nur 50% der Punkte. Gibt es keine Beschreibung und lediglich eine Liste von Fachbegriffen, dann kannst Du Dir sicher vorstellen, dass es **nix** gibt. 

### Beantwortung mit einem Rechenweg

Alle Rechnungen werden folgendermaßen angegangen:

#. Du stellst **immer** eine Ausgangsgleichung mit Variablen zur Berechnung des gewünschten Ergebnisses auf. Diese Gleichung beinhalten die **Variablen** mit dem entsprechenden Buchstaben, der in der Einführung mitgeteilt worden ist. Gibt es eine Abweichung, dann wird diese kenntlich gemacht.
#. In dieser Gleichung markierst Du jeweils die bekannten und unbekannten Variablen.
#. Falls notwendig, stellst Du die Gleichung anschliessend algebraisch um, so dass die beabsichtigte Berechnung klar wird. Hierbei werden **keine Zahlen oder Größen verwendet**.
#. Einsetzen der physikalischen Größen bestehend aus Zahlenwert und physikalischer Einheit in die Gleichung
#. Berechnung des Ergebnisses unter Berücksichtigung der Einheiten; dass heisst, die Rechnung ist nicht nur numerisch sondern auch bezüglich der Einheiten korrekt.

Es gibt jeweils einen Punkt für jeden dieser Schritte. Die einfachsten Aufgaben bringen maximal vier Punkte ein, da es noch nicht mal eine Umstellung der Ausgangsgleichung gibt. Es wird aber auch aufwändigere Aufgaben mit mehr Punkten geben. Die Gesamtnote 15 gibt es nur bei Erreichen der maximalen Punktanzahl.

## Anforderung

Es gibt drei Schwierigkeitsstufen bei den Aufgaben.

- Stufe I ist auf E Kurs Niveau angesiedelt. 
- Stufe II ist auf E oder A Niveau angesiedelt; manchmal dazwischen.
- Stufe III ist komplett auf A Kurs Niveau angesiedelt.

Da es nur noch eine Notenskala für die undifferenzierte Biologie gibt, solltest Du nicht nur Aufgaben auf Stufe I und II lösen. Um Dich darüber einzuordnen, solltest Du mit Regelmässigkeit Aufgaben aus Stufe II und II angehen.

### Berechnung der Gesamtnote

Deine Gesamtnote setzt sich aus folgenden Elementen zusammen:

- Schriftliche Mitarbeit oder Bearbeitung von Aufgaben: fließt zu mindestens 50% in die Zeugnisnote ein
    + Dabei berechnet sich die Gesamtnote für eine Aufgabenblock zu einer Einführung aus allen Aufgaben und deren Lösungen.
    + Wenn nicht benotet, dann erfolgt eine **00 Minderleistung** bei Nichteinreichen der Aufgaben 
- Mündliche Mitarbeit: regelmäßige Beiträge, heisst mindestens einmal pro Fachunterrichtseinheit, fließt zu höchstens 25% oder 1/4 in die Zeugnisnote ein
- Lernstandsüberprüfungen: fließt höchstens zu 25% oder 1/4 in die Zeugnisnote ein. Es besteht die Überlegung, LSÜs komplett zu ersetzen 

Die aktuelle Notenberechnung in Biologie Stufe 10 ist

$$
\mathrm{Zeugnis} = \frac{1}{2} \cdot \mathrm{Aufgaben} + \frac{1}{4} \cdot \mathrm{Mündlich} + \frac{1}{4} \cdot \mathrm{Schriftlich}
$$

Dabei sind alle Noten Durchschnittswerte pro Halbjahr.

::: {.callout-tip title="Beispiel"}

Du hast bei den Aufgaben eine 13, die mündliche Mitarbeit ist eine 08, und bei LSÜs hast Du 10. Dann ist Deine Zeugnisnote

$$
\frac{1}{2} \cdot 13 + \frac{1}{4} \cdot 8 + \frac{1}{4} \cdot 10 = 11
$$

:::

### Berechne Deine Zeugnisnote

Wähle Deine Durchschnittsnote mit den Schiebereglern:

```{ojs}
// task_grade = 10;
viewof task_grade = Inputs.range(
    [0, 15], 
    {value: 7, step: 1, label: "Durchschnitt bei Aufgabe:"}
)
viewof oral_grade = Inputs.range(
    [0, 15], 
    {value: 7, step: 1, label: "Durchschnitt mündlich:"}
)
viewof written_grade = Inputs.range(
    [0, 15], 
    {value: 7, step: 1, label: "Durchschnitt LSÜ:"}
)
```

```{ojs}
grade = 1/2 * task_grade + 1/4 * oral_grade + 1/4 * written_grade;
```
[Deine Zeugnisnote ist `{ojs} Math.round(grade)`.]{fg="red"} 

Die Berechnung ergibt manchmal Dezimalstellen. Diese wurden in einem Standardverfahren der mathematischen Rundung auf die nächstmögliche ganze Zahl gerundet.

